= Jakarta EE Specification Committee Operation

This document describes the practices of the Jakarta EE Specification Committee.

Changes to this document must be approved by a simple majority vote of the Jakarta EE specification committee, conducted via the public Jakarta EE Specification Committee (jakarta.ee-spec@eclipse.org) mailing list.

This is a public document.

== Project Lead(s) Designation
A specification project must designate one or more committers to serve as the project lead.
The lead is responsible for initiating reviews as the project reaches the appropriate milestone.

== Specification Committee Votes
Specification committee approval votes connected to progress and release reviews run for a minimum of 14 days; other votes run for a minimum of 7 days.

The requirements for each are described in <<process.adoc#,Review Requirements/Guidelines>>

The https://www.eclipse.org/projects/handbook/#release[standard release process] defined in the Eclipse Foundation Project Handbook is followed and augmented with a specification committee ballot. In short:

* The project team creates a release record as described in https://www.eclipse.org/projects/handbook/#pmi-commands-release
* The project team creates two PRs request against the Jakarta EE Specification Committee specifications repository. The first
PR provides everything requested in the PR template except the javadoc contents. The second PR would include the javadoc contents.
These PRs are intended to provide the items that are required to validate the release, and provide the jakarta.ee website
content for the specification. The github repository to create PRs against is https://github.com/jakartaee/specifications
* The project team requests approval for the release from the PMC by sending an email to ee4j-pmc@eclipse.org.
* The project team delivers an IP Log to the IP Team for their review as described in https://www.eclipse.org/projects/handbook/#pmi-commands-iplog
* The project team contacts the EMO to initiate the review by sending an email to emo@eclipse.org.
* The EMO initiates a specification committee ballot by sending an email on the public Jakarta EE Specification Committee
(jakarta.ee-spec@eclipse.org) mailing list that describes the nature of the vote (creation/progress/release) and includes
pointers to the PR request containing the proposed release content (e.g. release review document, specification document, and technical artifacts).

A specification committee member votes by responding to the ballot message on the public Jakarta EE Specification Committee mailing list, using the usual +1/0/-1 voting notation.

If a specification committee member votes against a motion, they must provide a comment that explains the reason for the negative vote and suggest steps to mitigate the issue.

The specification committee chair (or their designate) tallies the results of the vote, and aggregates the comments and presents them to the community via the specification project page on jakarta.ee, a summary email to jakarta.ee-community@eclipse.org, and a copies to jakarta.ee-spec@eclipse.org and emo@eclipse.org, within one week of the completion of the vote.

The specification committee may choose to extend the deadline for a vote by simple majority vote on the public specification committee mailing list (jakarta.ee-spec@eclipse.org).

In the event that a vote fails, the EMO will fail the corresponding review, forward the comments from the vote to the specification team, and invite them to resolve the issues and re-engage at a later date.

Note that the EMO schedules reviews to conclude on the first and third Wednesday of the month; this will impact the timing of the start of a specification committee vote and the timing of a project team re-engaging following a failed vote.
This means that specification committee chair must start the vote at least 14 days prior to the first and third Wednesday of the next month if they wish to minimize the time for the review to complete.
In the event that the specification committee opts to extend a vote, the EMO will, at its discretion, either bump the corresponding review to the next review slot or withhold approval of the review until the results of the specification committee vote are received.

== Participant Representative Appointments
A Member Participant may send a note to emo@eclipse.org to designate or remove their representative (a Member Participant’s representative must be covered by the Member Company’s MCCA and WGPA) as the Participant Representative (and Committer) for the Member Participant on any specification project associated with the Jakarta EE Working Group.

The EMO will maintain a record of participant representatives on the specification project’s PMI "Who's Involved" page in a section titled "Participant Representatives" (e.g. https://projects.eclipse.org/projects/ee4j.servlet/who[Eclipse Project for Servlets "Who's Involved"]).

== Developing Specifications
Specification projects in active development must engage in a progress or release review at least once per year as required by the JESP.
In practical terms, this means that the clock starts ticking when the plan review that occurs at the beginning of the development cycle concludes successfully, and is reset following a successful progress review.

The entire process is halted when either the specification project engages in a successful release review (thereby concluding the development cycle), or the specification team decides to abandon the cycle.

== Recommended Specification Project Repository Structure
The current recommendation for structure of the specification project repository is to have one *-spec repository with an api and spec subdirectory for the API and specification content, and a second *-tck repository for the TCK content.

== Distributing Specifications
Each specification project has a location on the jakarta.ee website under https://jakarta.ee/specifications/.

For each final specification:

* Links to specification documentation and all related artifacts including the TCK and compatible implementations that will be updated as new implementation are certified;
* Metadata, including version number and date of release
* Results of all specification committee votes

== Creating a Final Specification
A specification document that is marked "Final" cannot be made generally available until after engaging in a successful release review (with corresponding super-majority approval from the specification committee).
A release review will have validated that the specification project has:

1. Produced a staging release via OSSRH staging repository for the api, javadoc. The specification would be staged on a github release marked as pre-release.
2. Attached the candidate final specification to the release in English
3. The candidate final EFTL licensed TCK archive should be uploaded to the project directory under download.eclipse.org.
The github release should have a link to the candidate EFTL licensed artifact.
There is no need to produce a final EPL version?
Question on issues with using mirrored links.
4. Attached the EFTL TCK summary results for each implementation included with this release review.
5. Create two https://help.github.com/en/articles/about-pull-requests#draft-pull-requests[draft PRs] request against the
https://github.com/jakartaee/specifications[Jakarta EE Specification Committee specifications] repository. The first PR
provides everything requested in the PR template except the javadoc contents. The second PR would include the javadoc contents.
These PRs are intended to provide the items that are required to validate the release, and provide the jakarta.ee website content
for the specification. There is a PR template that guides what to include in the PR.

After the release review has completed successfully, the final release needs to be promoted to maven central.
The specification committee will promote the specification project to jakarta.ee by merging the associated PR into the Jakarta EE Specification Committee project repository.

Links: https://github.com/jakartaee/jakarta.ee, https://gohugo.io/documentation/

== Review Requirements/Guidelines
The EMO validates:

* That the review material meets a minimum standard (meaningful description);
* That the project repository includes the required legal documentation; and
* That the Eclipse Intellectual Property Due Diligence process has been followed.

The PMC validates:

* That the Eclipse Development Process has been followed;
* That the project is operating in an open and transparent manner;
* That the specification document is consistent with established conventions;and
* That the project has no unreasonable barriers for participation.
* That the submission material is complete

The Specification Committee validates:

* That the content presented for review is in scope;
* That the website documentation adequately and consistently describes the specification(s); and
* That the specification document is consistent with established conventions and meets the necessary quality standards.
* For a Progress Review, that sufficient progress has been made on a Compatible Implementation and TCK, to ensure that the spec is implementable and testable.
* For a Release Review, that a Compatible Implementation is complete, passes the TCK, and that the TCK includes sufficient coverage of the specification.
The TCK users guide MUST include the instructions to run the compatible implementations used to validate the release.
Instructions MAY be by reference.

== Namespaces

=== Maven
The maven group id, artifact id, and artifact names should follow the rules described in the https://wiki.eclipse.org/JakartaEE_Maven_Versioning_Rules document.

=== Java Package
All new classes, as well as modifications to `javax.*` classes, are created in the `jakarta.{abbreviation}.*` package.

This also applies to OSGi bundles produced by the project.

=== Exceptions
Petition the specification committee to request an exception to the namespace rules above.

== Coding Conventions
Where feasible, all source content must include a valid copyright and license header.
Tools such as the `https://github.com/javaee/copyright-maven-plugin[glassfish-copyright-maven-plugin]` may be useful in ensuring consistency.

== Specification Document Conventions (Currently under discussion)
Written in the third person tense

TBD "uses" vs. "includes"

Recommended formats, in order of preference: asciidoc, markdown, text.

The first reference to other specifications must use the official full name.
Subsequent references may use a generally accepted abbreviation.

== Initial Migration Tasks
The requirements for the initial migration from the legacy Java EE projects and associated naming conventions to the Jakarta conventions is outlined in these documents:

* https://jakarta.ee/legal/acronym_guidelines/[Oracle/JCP Acronym Guidelines]
* <<names.adoc#,Project Names and Codes>>

Using these conventions, projects need to:

* Change the specification name to that given in <<names.adoc#,Project Names and Codes>>
* JavaDocs and text documents such as README files need to be updated to use these naming conventions.
* Replace references to JCP process with references to https://jakarta.ee/about/jesp/[Eclipse JESP]
* Update references to other specifications to use name in <<names.adoc#,Project Names and Codes>>
* Links to JCP JSR pages need to be replaced with a links of the form jakarta.ee/specifications/<code>/<version> where <code> is the specification code from <<names.adoc#,Project Names and Codes>>, and <version> is the particular specification version.

Specification projects need issue templates and labels to support the TCK challenge process, and the compatibility request process.
Creating an issue template is described in this GitHub doc: https://help.github.com/en/articles/creating-issue-templates-for-your-repository.
Creating labels is described in this GitHub doc: https://help.github.com/en/articles/creating-a-label.

The current TCK challenge and compatibility request process requires the following issue labels, which should be defined in the issue tracker:

[options="header"]
|===
| Label | Description
| challenge | TCK challenge
| accepted | Accepted certification request
| challenge-appeal | Appeal a rejected TCK challenge
| appealed-challenge | TCK challenge was appealed
| certification | Compatibility certification request
| invalid | This doesn't seem right (label already exists)
| enhancement | New feature or request (label already exists)
|===


Finally, follow https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release[How to Prepare API Projects to Jakarta EE 8 Release] to create an initial Jakarta EE 8 release.
